//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace MES_WATER.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WmsApiSoap", Namespace="http://www.wmsapi.com.tw/")]
    public partial class WmsApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ErrorRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback BANCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback Decimal_RoundOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PreviousYMOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_NextYMOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserParaValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback NumTo_RocNo2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutoInt2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStvExchangeRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTKCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Rep_ZeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChkNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ProTotalQtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_One_StoQtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_DAFirstCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_All_StoQtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_StoQtyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ProCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback Cal_TraQtyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WmsApi() {
            this.Url = global::MES_WATER.Properties.Settings.Default.MES_WATER_WebReference_WmsApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ErrorRecordCompletedEventHandler ErrorRecordCompleted;
        
        /// <remarks/>
        public event BANCheckCompletedEventHandler BANCheckCompleted;
        
        /// <remarks/>
        public event CheckIdCompletedEventHandler CheckIdCompleted;
        
        /// <remarks/>
        public event Decimal_RoundCompletedEventHandler Decimal_RoundCompleted;
        
        /// <remarks/>
        public event Get_PreviousYMCompletedEventHandler Get_PreviousYMCompleted;
        
        /// <remarks/>
        public event Get_NextYMCompletedEventHandler Get_NextYMCompleted;
        
        /// <remarks/>
        public event UserParaValueCompletedEventHandler UserParaValueCompleted;
        
        /// <remarks/>
        public event NumTo_RocNo2CompletedEventHandler NumTo_RocNo2Completed;
        
        /// <remarks/>
        public event ChangeStringCompletedEventHandler ChangeStringCompleted;
        
        /// <remarks/>
        public event ParaValueCompletedEventHandler ParaValueCompleted;
        
        /// <remarks/>
        public event AutoInt2CompletedEventHandler AutoInt2Completed;
        
        /// <remarks/>
        public event GetStvExchangeRateCompletedEventHandler GetStvExchangeRateCompleted;
        
        /// <remarks/>
        public event GetTKCodeCompletedEventHandler GetTKCodeCompleted;
        
        /// <remarks/>
        public event Rep_ZeroCompletedEventHandler Rep_ZeroCompleted;
        
        /// <remarks/>
        public event GetChkNumCompletedEventHandler GetChkNumCompleted;
        
        /// <remarks/>
        public event Get_ProTotalQtyCompletedEventHandler Get_ProTotalQtyCompleted;
        
        /// <remarks/>
        public event Update_One_StoQtyCompletedEventHandler Update_One_StoQtyCompleted;
        
        /// <remarks/>
        public event Update_DAFirstCostCompletedEventHandler Update_DAFirstCostCompleted;
        
        /// <remarks/>
        public event Update_All_StoQtyCompletedEventHandler Update_All_StoQtyCompleted;
        
        /// <remarks/>
        public event Get_StoQtyCompletedEventHandler Get_StoQtyCompleted;
        
        /// <remarks/>
        public event Get_ProCostCompletedEventHandler Get_ProCostCompleted;
        
        /// <remarks/>
        public event Cal_TraQtyCompletedEventHandler Cal_TraQtyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/ErrorRecord", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ErrorRecord(string vErrText, string vFunction_name) {
            object[] results = this.Invoke("ErrorRecord", new object[] {
                        vErrText,
                        vFunction_name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ErrorRecordAsync(string vErrText, string vFunction_name) {
            this.ErrorRecordAsync(vErrText, vFunction_name, null);
        }
        
        /// <remarks/>
        public void ErrorRecordAsync(string vErrText, string vFunction_name, object userState) {
            if ((this.ErrorRecordOperationCompleted == null)) {
                this.ErrorRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnErrorRecordOperationCompleted);
            }
            this.InvokeAsync("ErrorRecord", new object[] {
                        vErrText,
                        vFunction_name}, this.ErrorRecordOperationCompleted, userState);
        }
        
        private void OnErrorRecordOperationCompleted(object arg) {
            if ((this.ErrorRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ErrorRecordCompleted(this, new ErrorRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/BANCheck", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool BANCheck(string strBAN, ref string strReason) {
            object[] results = this.Invoke("BANCheck", new object[] {
                        strBAN,
                        strReason});
            strReason = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BANCheckAsync(string strBAN, string strReason) {
            this.BANCheckAsync(strBAN, strReason, null);
        }
        
        /// <remarks/>
        public void BANCheckAsync(string strBAN, string strReason, object userState) {
            if ((this.BANCheckOperationCompleted == null)) {
                this.BANCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBANCheckOperationCompleted);
            }
            this.InvokeAsync("BANCheck", new object[] {
                        strBAN,
                        strReason}, this.BANCheckOperationCompleted, userState);
        }
        
        private void OnBANCheckOperationCompleted(object arg) {
            if ((this.BANCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BANCheckCompleted(this, new BANCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/CheckId", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckId(string strUserID, ref string strReason) {
            object[] results = this.Invoke("CheckId", new object[] {
                        strUserID,
                        strReason});
            strReason = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckIdAsync(string strUserID, string strReason) {
            this.CheckIdAsync(strUserID, strReason, null);
        }
        
        /// <remarks/>
        public void CheckIdAsync(string strUserID, string strReason, object userState) {
            if ((this.CheckIdOperationCompleted == null)) {
                this.CheckIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckIdOperationCompleted);
            }
            this.InvokeAsync("CheckId", new object[] {
                        strUserID,
                        strReason}, this.CheckIdOperationCompleted, userState);
        }
        
        private void OnCheckIdOperationCompleted(object arg) {
            if ((this.CheckIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckIdCompleted(this, new CheckIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Decimal_Round", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long Decimal_Round(double C_num, string Round_Type) {
            object[] results = this.Invoke("Decimal_Round", new object[] {
                        C_num,
                        Round_Type});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void Decimal_RoundAsync(double C_num, string Round_Type) {
            this.Decimal_RoundAsync(C_num, Round_Type, null);
        }
        
        /// <remarks/>
        public void Decimal_RoundAsync(double C_num, string Round_Type, object userState) {
            if ((this.Decimal_RoundOperationCompleted == null)) {
                this.Decimal_RoundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDecimal_RoundOperationCompleted);
            }
            this.InvokeAsync("Decimal_Round", new object[] {
                        C_num,
                        Round_Type}, this.Decimal_RoundOperationCompleted, userState);
        }
        
        private void OnDecimal_RoundOperationCompleted(object arg) {
            if ((this.Decimal_RoundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Decimal_RoundCompleted(this, new Decimal_RoundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Get_PreviousYM", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_PreviousYM(string Cur_yymm) {
            object[] results = this.Invoke("Get_PreviousYM", new object[] {
                        Cur_yymm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_PreviousYMAsync(string Cur_yymm) {
            this.Get_PreviousYMAsync(Cur_yymm, null);
        }
        
        /// <remarks/>
        public void Get_PreviousYMAsync(string Cur_yymm, object userState) {
            if ((this.Get_PreviousYMOperationCompleted == null)) {
                this.Get_PreviousYMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PreviousYMOperationCompleted);
            }
            this.InvokeAsync("Get_PreviousYM", new object[] {
                        Cur_yymm}, this.Get_PreviousYMOperationCompleted, userState);
        }
        
        private void OnGet_PreviousYMOperationCompleted(object arg) {
            if ((this.Get_PreviousYMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PreviousYMCompleted(this, new Get_PreviousYMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Get_NextYM", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_NextYM(string Cur_yymm) {
            object[] results = this.Invoke("Get_NextYM", new object[] {
                        Cur_yymm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_NextYMAsync(string Cur_yymm) {
            this.Get_NextYMAsync(Cur_yymm, null);
        }
        
        /// <remarks/>
        public void Get_NextYMAsync(string Cur_yymm, object userState) {
            if ((this.Get_NextYMOperationCompleted == null)) {
                this.Get_NextYMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_NextYMOperationCompleted);
            }
            this.InvokeAsync("Get_NextYM", new object[] {
                        Cur_yymm}, this.Get_NextYMOperationCompleted, userState);
        }
        
        private void OnGet_NextYMOperationCompleted(object arg) {
            if ((this.Get_NextYMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_NextYMCompleted(this, new Get_NextYMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/UserParaValue", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserParaValue(string Par_name, string Default_value) {
            object[] results = this.Invoke("UserParaValue", new object[] {
                        Par_name,
                        Default_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserParaValueAsync(string Par_name, string Default_value) {
            this.UserParaValueAsync(Par_name, Default_value, null);
        }
        
        /// <remarks/>
        public void UserParaValueAsync(string Par_name, string Default_value, object userState) {
            if ((this.UserParaValueOperationCompleted == null)) {
                this.UserParaValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserParaValueOperationCompleted);
            }
            this.InvokeAsync("UserParaValue", new object[] {
                        Par_name,
                        Default_value}, this.UserParaValueOperationCompleted, userState);
        }
        
        private void OnUserParaValueOperationCompleted(object arg) {
            if ((this.UserParaValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserParaValueCompleted(this, new UserParaValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/NumTo_RocNo2", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NumTo_RocNo2(string curNumber, bool Add_str) {
            object[] results = this.Invoke("NumTo_RocNo2", new object[] {
                        curNumber,
                        Add_str});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NumTo_RocNo2Async(string curNumber, bool Add_str) {
            this.NumTo_RocNo2Async(curNumber, Add_str, null);
        }
        
        /// <remarks/>
        public void NumTo_RocNo2Async(string curNumber, bool Add_str, object userState) {
            if ((this.NumTo_RocNo2OperationCompleted == null)) {
                this.NumTo_RocNo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnNumTo_RocNo2OperationCompleted);
            }
            this.InvokeAsync("NumTo_RocNo2", new object[] {
                        curNumber,
                        Add_str}, this.NumTo_RocNo2OperationCompleted, userState);
        }
        
        private void OnNumTo_RocNo2OperationCompleted(object arg) {
            if ((this.NumTo_RocNo2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NumTo_RocNo2Completed(this, new NumTo_RocNo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/ChangeString", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChangeString(string C_str, string C_type) {
            object[] results = this.Invoke("ChangeString", new object[] {
                        C_str,
                        C_type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeStringAsync(string C_str, string C_type) {
            this.ChangeStringAsync(C_str, C_type, null);
        }
        
        /// <remarks/>
        public void ChangeStringAsync(string C_str, string C_type, object userState) {
            if ((this.ChangeStringOperationCompleted == null)) {
                this.ChangeStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeStringOperationCompleted);
            }
            this.InvokeAsync("ChangeString", new object[] {
                        C_str,
                        C_type}, this.ChangeStringOperationCompleted, userState);
        }
        
        private void OnChangeStringOperationCompleted(object arg) {
            if ((this.ChangeStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeStringCompleted(this, new ChangeStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/ParaValue", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ParaValue(string Par_name, string Sys_code, string Prg_code, string Default_value) {
            object[] results = this.Invoke("ParaValue", new object[] {
                        Par_name,
                        Sys_code,
                        Prg_code,
                        Default_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ParaValueAsync(string Par_name, string Sys_code, string Prg_code, string Default_value) {
            this.ParaValueAsync(Par_name, Sys_code, Prg_code, Default_value, null);
        }
        
        /// <remarks/>
        public void ParaValueAsync(string Par_name, string Sys_code, string Prg_code, string Default_value, object userState) {
            if ((this.ParaValueOperationCompleted == null)) {
                this.ParaValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaValueOperationCompleted);
            }
            this.InvokeAsync("ParaValue", new object[] {
                        Par_name,
                        Sys_code,
                        Prg_code,
                        Default_value}, this.ParaValueOperationCompleted, userState);
        }
        
        private void OnParaValueOperationCompleted(object arg) {
            if ((this.ParaValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaValueCompleted(this, new ParaValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/AutoInt2", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long AutoInt2(string TableName) {
            object[] results = this.Invoke("AutoInt2", new object[] {
                        TableName});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void AutoInt2Async(string TableName) {
            this.AutoInt2Async(TableName, null);
        }
        
        /// <remarks/>
        public void AutoInt2Async(string TableName, object userState) {
            if ((this.AutoInt2OperationCompleted == null)) {
                this.AutoInt2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutoInt2OperationCompleted);
            }
            this.InvokeAsync("AutoInt2", new object[] {
                        TableName}, this.AutoInt2OperationCompleted, userState);
        }
        
        private void OnAutoInt2OperationCompleted(object arg) {
            if ((this.AutoInt2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutoInt2Completed(this, new AutoInt2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/GetStvExchangeRate", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetStvExchangeRate(string BillDate, string pStv_code) {
            object[] results = this.Invoke("GetStvExchangeRate", new object[] {
                        BillDate,
                        pStv_code});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetStvExchangeRateAsync(string BillDate, string pStv_code) {
            this.GetStvExchangeRateAsync(BillDate, pStv_code, null);
        }
        
        /// <remarks/>
        public void GetStvExchangeRateAsync(string BillDate, string pStv_code, object userState) {
            if ((this.GetStvExchangeRateOperationCompleted == null)) {
                this.GetStvExchangeRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStvExchangeRateOperationCompleted);
            }
            this.InvokeAsync("GetStvExchangeRate", new object[] {
                        BillDate,
                        pStv_code}, this.GetStvExchangeRateOperationCompleted, userState);
        }
        
        private void OnGetStvExchangeRateOperationCompleted(object arg) {
            if ((this.GetStvExchangeRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStvExchangeRateCompleted(this, new GetStvExchangeRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/GetTKCode", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTKCode(string Prg_code, string Tk_date, bool NeedRefresh, string Dash_code2, int User_serial) {
            object[] results = this.Invoke("GetTKCode", new object[] {
                        Prg_code,
                        Tk_date,
                        NeedRefresh,
                        Dash_code2,
                        User_serial});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTKCodeAsync(string Prg_code, string Tk_date, bool NeedRefresh, string Dash_code2, int User_serial) {
            this.GetTKCodeAsync(Prg_code, Tk_date, NeedRefresh, Dash_code2, User_serial, null);
        }
        
        /// <remarks/>
        public void GetTKCodeAsync(string Prg_code, string Tk_date, bool NeedRefresh, string Dash_code2, int User_serial, object userState) {
            if ((this.GetTKCodeOperationCompleted == null)) {
                this.GetTKCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTKCodeOperationCompleted);
            }
            this.InvokeAsync("GetTKCode", new object[] {
                        Prg_code,
                        Tk_date,
                        NeedRefresh,
                        Dash_code2,
                        User_serial}, this.GetTKCodeOperationCompleted, userState);
        }
        
        private void OnGetTKCodeOperationCompleted(object arg) {
            if ((this.GetTKCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTKCodeCompleted(this, new GetTKCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Rep_Zero", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Rep_Zero(int sSerialNum) {
            object[] results = this.Invoke("Rep_Zero", new object[] {
                        sSerialNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Rep_ZeroAsync(int sSerialNum) {
            this.Rep_ZeroAsync(sSerialNum, null);
        }
        
        /// <remarks/>
        public void Rep_ZeroAsync(int sSerialNum, object userState) {
            if ((this.Rep_ZeroOperationCompleted == null)) {
                this.Rep_ZeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRep_ZeroOperationCompleted);
            }
            this.InvokeAsync("Rep_Zero", new object[] {
                        sSerialNum}, this.Rep_ZeroOperationCompleted, userState);
        }
        
        private void OnRep_ZeroOperationCompleted(object arg) {
            if ((this.Rep_ZeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Rep_ZeroCompleted(this, new Rep_ZeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/GetChkNum", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetChkNum(string Inv_code) {
            object[] results = this.Invoke("GetChkNum", new object[] {
                        Inv_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetChkNumAsync(string Inv_code) {
            this.GetChkNumAsync(Inv_code, null);
        }
        
        /// <remarks/>
        public void GetChkNumAsync(string Inv_code, object userState) {
            if ((this.GetChkNumOperationCompleted == null)) {
                this.GetChkNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChkNumOperationCompleted);
            }
            this.InvokeAsync("GetChkNum", new object[] {
                        Inv_code}, this.GetChkNumOperationCompleted, userState);
        }
        
        private void OnGetChkNumOperationCompleted(object arg) {
            if ((this.GetChkNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChkNumCompleted(this, new GetChkNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Get_ProTotalQty", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Get_ProTotalQty(string Sto_date, string Limit_str, string Pro_code, string Sto_code, string Lot_no, string Exp_date, string NumberFormat, bool PassLotno) {
            object[] results = this.Invoke("Get_ProTotalQty", new object[] {
                        Sto_date,
                        Limit_str,
                        Pro_code,
                        Sto_code,
                        Lot_no,
                        Exp_date,
                        NumberFormat,
                        PassLotno});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ProTotalQtyAsync(string Sto_date, string Limit_str, string Pro_code, string Sto_code, string Lot_no, string Exp_date, string NumberFormat, bool PassLotno) {
            this.Get_ProTotalQtyAsync(Sto_date, Limit_str, Pro_code, Sto_code, Lot_no, Exp_date, NumberFormat, PassLotno, null);
        }
        
        /// <remarks/>
        public void Get_ProTotalQtyAsync(string Sto_date, string Limit_str, string Pro_code, string Sto_code, string Lot_no, string Exp_date, string NumberFormat, bool PassLotno, object userState) {
            if ((this.Get_ProTotalQtyOperationCompleted == null)) {
                this.Get_ProTotalQtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ProTotalQtyOperationCompleted);
            }
            this.InvokeAsync("Get_ProTotalQty", new object[] {
                        Sto_date,
                        Limit_str,
                        Pro_code,
                        Sto_code,
                        Lot_no,
                        Exp_date,
                        NumberFormat,
                        PassLotno}, this.Get_ProTotalQtyOperationCompleted, userState);
        }
        
        private void OnGet_ProTotalQtyOperationCompleted(object arg) {
            if ((this.Get_ProTotalQtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ProTotalQtyCompleted(this, new Get_ProTotalQtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Update_One_StoQty", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update_One_StoQty(double Cqty_type, string Cpro_code, string Csto_code, string Csto_date, double Csto_qty, double Csto_amt, bool Is_update, string Csto_type, string Clot_no, string Cexp_date) {
            object[] results = this.Invoke("Update_One_StoQty", new object[] {
                        Cqty_type,
                        Cpro_code,
                        Csto_code,
                        Csto_date,
                        Csto_qty,
                        Csto_amt,
                        Is_update,
                        Csto_type,
                        Clot_no,
                        Cexp_date});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update_One_StoQtyAsync(double Cqty_type, string Cpro_code, string Csto_code, string Csto_date, double Csto_qty, double Csto_amt, bool Is_update, string Csto_type, string Clot_no, string Cexp_date) {
            this.Update_One_StoQtyAsync(Cqty_type, Cpro_code, Csto_code, Csto_date, Csto_qty, Csto_amt, Is_update, Csto_type, Clot_no, Cexp_date, null);
        }
        
        /// <remarks/>
        public void Update_One_StoQtyAsync(double Cqty_type, string Cpro_code, string Csto_code, string Csto_date, double Csto_qty, double Csto_amt, bool Is_update, string Csto_type, string Clot_no, string Cexp_date, object userState) {
            if ((this.Update_One_StoQtyOperationCompleted == null)) {
                this.Update_One_StoQtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_One_StoQtyOperationCompleted);
            }
            this.InvokeAsync("Update_One_StoQty", new object[] {
                        Cqty_type,
                        Cpro_code,
                        Csto_code,
                        Csto_date,
                        Csto_qty,
                        Csto_amt,
                        Is_update,
                        Csto_type,
                        Clot_no,
                        Cexp_date}, this.Update_One_StoQtyOperationCompleted, userState);
        }
        
        private void OnUpdate_One_StoQtyOperationCompleted(object arg) {
            if ((this.Update_One_StoQtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_One_StoQtyCompleted(this, new Update_One_StoQtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Update_DAFirstCost", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update_DAFirstCost(string Cpro_code, string Csto_date) {
            object[] results = this.Invoke("Update_DAFirstCost", new object[] {
                        Cpro_code,
                        Csto_date});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update_DAFirstCostAsync(string Cpro_code, string Csto_date) {
            this.Update_DAFirstCostAsync(Cpro_code, Csto_date, null);
        }
        
        /// <remarks/>
        public void Update_DAFirstCostAsync(string Cpro_code, string Csto_date, object userState) {
            if ((this.Update_DAFirstCostOperationCompleted == null)) {
                this.Update_DAFirstCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_DAFirstCostOperationCompleted);
            }
            this.InvokeAsync("Update_DAFirstCost", new object[] {
                        Cpro_code,
                        Csto_date}, this.Update_DAFirstCostOperationCompleted, userState);
        }
        
        private void OnUpdate_DAFirstCostOperationCompleted(object arg) {
            if ((this.Update_DAFirstCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_DAFirstCostCompleted(this, new Update_DAFirstCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Update_All_StoQty", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update_All_StoQty(double Cqty_type, string Res_pro, string Csto_date, string Csto_type) {
            object[] results = this.Invoke("Update_All_StoQty", new object[] {
                        Cqty_type,
                        Res_pro,
                        Csto_date,
                        Csto_type});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update_All_StoQtyAsync(double Cqty_type, string Res_pro, string Csto_date, string Csto_type) {
            this.Update_All_StoQtyAsync(Cqty_type, Res_pro, Csto_date, Csto_type, null);
        }
        
        /// <remarks/>
        public void Update_All_StoQtyAsync(double Cqty_type, string Res_pro, string Csto_date, string Csto_type, object userState) {
            if ((this.Update_All_StoQtyOperationCompleted == null)) {
                this.Update_All_StoQtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_All_StoQtyOperationCompleted);
            }
            this.InvokeAsync("Update_All_StoQty", new object[] {
                        Cqty_type,
                        Res_pro,
                        Csto_date,
                        Csto_type}, this.Update_All_StoQtyOperationCompleted, userState);
        }
        
        private void OnUpdate_All_StoQtyOperationCompleted(object arg) {
            if ((this.Update_All_StoQtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_All_StoQtyCompleted(this, new Update_All_StoQtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Get_StoQty", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Get_StoQty(string Cpro_code, string Csto_code, string Csto_date, string Clot_no, string Cexp_date, bool PassCheck, bool PassLotno) {
            object[] results = this.Invoke("Get_StoQty", new object[] {
                        Cpro_code,
                        Csto_code,
                        Csto_date,
                        Clot_no,
                        Cexp_date,
                        PassCheck,
                        PassLotno});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Get_StoQtyAsync(string Cpro_code, string Csto_code, string Csto_date, string Clot_no, string Cexp_date, bool PassCheck, bool PassLotno) {
            this.Get_StoQtyAsync(Cpro_code, Csto_code, Csto_date, Clot_no, Cexp_date, PassCheck, PassLotno, null);
        }
        
        /// <remarks/>
        public void Get_StoQtyAsync(string Cpro_code, string Csto_code, string Csto_date, string Clot_no, string Cexp_date, bool PassCheck, bool PassLotno, object userState) {
            if ((this.Get_StoQtyOperationCompleted == null)) {
                this.Get_StoQtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_StoQtyOperationCompleted);
            }
            this.InvokeAsync("Get_StoQty", new object[] {
                        Cpro_code,
                        Csto_code,
                        Csto_date,
                        Clot_no,
                        Cexp_date,
                        PassCheck,
                        PassLotno}, this.Get_StoQtyOperationCompleted, userState);
        }
        
        private void OnGet_StoQtyOperationCompleted(object arg) {
            if ((this.Get_StoQtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_StoQtyCompleted(this, new Get_StoQtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Get_ProCost", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Get_ProCost(string Cpro_code, string Csto_date, string Clot_no, string Cexp_date, string Cost_kind) {
            object[] results = this.Invoke("Get_ProCost", new object[] {
                        Cpro_code,
                        Csto_date,
                        Clot_no,
                        Cexp_date,
                        Cost_kind});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ProCostAsync(string Cpro_code, string Csto_date, string Clot_no, string Cexp_date, string Cost_kind) {
            this.Get_ProCostAsync(Cpro_code, Csto_date, Clot_no, Cexp_date, Cost_kind, null);
        }
        
        /// <remarks/>
        public void Get_ProCostAsync(string Cpro_code, string Csto_date, string Clot_no, string Cexp_date, string Cost_kind, object userState) {
            if ((this.Get_ProCostOperationCompleted == null)) {
                this.Get_ProCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ProCostOperationCompleted);
            }
            this.InvokeAsync("Get_ProCost", new object[] {
                        Cpro_code,
                        Csto_date,
                        Clot_no,
                        Cexp_date,
                        Cost_kind}, this.Get_ProCostOperationCompleted, userState);
        }
        
        private void OnGet_ProCostOperationCompleted(object arg) {
            if ((this.Get_ProCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ProCostCompleted(this, new Get_ProCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Cal_TraQty", RequestNamespace="http://www.wmsapi.com.tw/", ResponseNamespace="http://www.wmsapi.com.tw/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Cal_TraQty(string pType, string pSor_table, string pSor_qty, double pPro_qty, string pWhere) {
            object[] results = this.Invoke("Cal_TraQty", new object[] {
                        pType,
                        pSor_table,
                        pSor_qty,
                        pPro_qty,
                        pWhere});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Cal_TraQtyAsync(string pType, string pSor_table, string pSor_qty, double pPro_qty, string pWhere) {
            this.Cal_TraQtyAsync(pType, pSor_table, pSor_qty, pPro_qty, pWhere, null);
        }
        
        /// <remarks/>
        public void Cal_TraQtyAsync(string pType, string pSor_table, string pSor_qty, double pPro_qty, string pWhere, object userState) {
            if ((this.Cal_TraQtyOperationCompleted == null)) {
                this.Cal_TraQtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCal_TraQtyOperationCompleted);
            }
            this.InvokeAsync("Cal_TraQty", new object[] {
                        pType,
                        pSor_table,
                        pSor_qty,
                        pPro_qty,
                        pWhere}, this.Cal_TraQtyOperationCompleted, userState);
        }
        
        private void OnCal_TraQtyOperationCompleted(object arg) {
            if ((this.Cal_TraQtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Cal_TraQtyCompleted(this, new Cal_TraQtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// 寫入上工資料
        /// </summary>
        /// <param name="pToken"></param>
        /// <param name="JSON"></param>
        /// <returns></returns>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Ins_Login", RequestNamespace = "http://www.wmsapi.com.tw/", ResponseNamespace = "http://www.wmsapi.com.tw/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ins_Login(string pToken,string JSON)
        {
            object[] results = this.Invoke("Ins_Login", new object[] {
                        pToken,
                        JSON,
                        });
            return ((string)(results[0]));
        }

        /// <summary>
        /// 寫入下工資料
        /// </summary>
        /// <param name="pToken"></param>
        /// <param name="JSON"></param>
        /// <returns></returns>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Ins_Logout", RequestNamespace = "http://www.wmsapi.com.tw/", ResponseNamespace = "http://www.wmsapi.com.tw/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ins_Logout(string pToken, string JSON)
        {
            object[] results = this.Invoke("Ins_Login", new object[] {
                        pToken,
                        JSON,
                        });
            return ((string)(results[0]));
        }

        /// <summary>
        /// 傳入日期及機台編號取得當日計畫上料順序及用料量
        /// </summary>
        /// <param name="pToken"></param>
        /// <param name="JSON"></param>
        /// <returns></returns>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Get_PreparList", RequestNamespace = "http://www.wmsapi.com.tw/", ResponseNamespace = "http://www.wmsapi.com.tw/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_PreparList(string pToken, string pDate,string pMacCode)
        {
            object[] results = this.Invoke("Ins_Login", new object[] {
                        pToken,
                        pDate,
                        pMacCode,
                        });
            return ((string)(results[0]));
        }

        /// <summary>
        /// 寫入停機原因
        /// </summary>
        /// <param name="pToken"></param>
        /// <param name="JSON"></param>
        /// <returns></returns>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wmsapi.com.tw/Ins_StopData", RequestNamespace = "http://www.wmsapi.com.tw/", ResponseNamespace = "http://www.wmsapi.com.tw/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ins_StopData(string pToken, string JSON)
        {
            object[] results = this.Invoke("Ins_Login", new object[] {
                        pToken,
                        JSON,
                        });
            return ((string)(results[0]));
        }



    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ErrorRecordCompletedEventHandler(object sender, ErrorRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ErrorRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void BANCheckCompletedEventHandler(object sender, BANCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BANCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BANCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strReason {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckIdCompletedEventHandler(object sender, CheckIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strReason {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Decimal_RoundCompletedEventHandler(object sender, Decimal_RoundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Decimal_RoundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Decimal_RoundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Get_PreviousYMCompletedEventHandler(object sender, Get_PreviousYMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PreviousYMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PreviousYMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Get_NextYMCompletedEventHandler(object sender, Get_NextYMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_NextYMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_NextYMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UserParaValueCompletedEventHandler(object sender, UserParaValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserParaValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserParaValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void NumTo_RocNo2CompletedEventHandler(object sender, NumTo_RocNo2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NumTo_RocNo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NumTo_RocNo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ChangeStringCompletedEventHandler(object sender, ChangeStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ParaValueCompletedEventHandler(object sender, ParaValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParaValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParaValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AutoInt2CompletedEventHandler(object sender, AutoInt2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutoInt2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutoInt2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetStvExchangeRateCompletedEventHandler(object sender, GetStvExchangeRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStvExchangeRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStvExchangeRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTKCodeCompletedEventHandler(object sender, GetTKCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTKCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTKCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Rep_ZeroCompletedEventHandler(object sender, Rep_ZeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Rep_ZeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Rep_ZeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetChkNumCompletedEventHandler(object sender, GetChkNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChkNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChkNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Get_ProTotalQtyCompletedEventHandler(object sender, Get_ProTotalQtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ProTotalQtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ProTotalQtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Update_One_StoQtyCompletedEventHandler(object sender, Update_One_StoQtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_One_StoQtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_One_StoQtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Update_DAFirstCostCompletedEventHandler(object sender, Update_DAFirstCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_DAFirstCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_DAFirstCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Update_All_StoQtyCompletedEventHandler(object sender, Update_All_StoQtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_All_StoQtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_All_StoQtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Get_StoQtyCompletedEventHandler(object sender, Get_StoQtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_StoQtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_StoQtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Get_ProCostCompletedEventHandler(object sender, Get_ProCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ProCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ProCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Cal_TraQtyCompletedEventHandler(object sender, Cal_TraQtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cal_TraQtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Cal_TraQtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    


}

#pragma warning restore 1591